// Generated by designlang v7.0.0
// Source: http://127.0.0.1:63847/fixture.html
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF2563EB);
  static const Color actionSecondary = Color(0xFF0F172A);
  static const Color actionOnPrimary = Color(0xFFFFFFFF);
  static const Color actionOnSecondary = Color(0xFFFFFFFF);
  static const Color actionAccent = Color(0xFFCBD5E1);
  static const Color actionOnAccent = Color(0xFF000000);
  static const Color surfaceDefault = Color(0xFFF8FAFC);
  static const Color surfacePage = Color(0xFFF8FAFC);
  static const Color surfaceOnPage = Color(0xFF000000);
  static const Color surfaceRaised = Color(0xFFFFFFFF);
  static const Color surfaceOnRaised = Color(0xFF000000);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 8;
  static const double spacingS1 = 80;
  static const double radiusR0 = 8;
  static const double radiusR1 = 12;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF2563EB);
  static const Color brandSecondary = Color(0xFF0F172A);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF475569);
  static const Color neutralN400 = Color(0xFF94A3B8);
  static const Color backgroundBg0 = Color(0xFFF8FAFC);
  static const Color backgroundBg1 = Color(0xFFFFFFFF);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF0F172A);
  static const Color textText2 = Color(0xFF2563EB);
  static const Color textText3 = Color(0xFF475569);
  static const Color textText4 = Color(0xFFFFFFFF);
  static const Color textText5 = Color(0xFFCBD5E1);
  static const Color rampPrimary50 = Color(0xFFC7F5FF);
  static const Color rampPrimary100 = Color(0xFFB7E9FF);
  static const Color rampPrimary200 = Color(0xFFA0D7FF);
  static const Color rampPrimary300 = Color(0xFF80BCFF);
  static const Color rampPrimary400 = Color(0xFF5798FF);
  static const Color rampPrimary500 = Color(0xFF3777FF);
  static const Color rampPrimary600 = Color(0xFF2563EB);
  static const Color rampPrimary700 = Color(0xFF164ABE);
  static const Color rampPrimary800 = Color(0xFF0C3BA1);
  static const Color rampPrimary900 = Color(0xFF052D87);
  static const Color rampPrimary950 = Color(0xFF001654);
  static const Color rampSecondary50 = Color(0xFFEEF6FF);
  static const Color rampSecondary100 = Color(0xFFE1EAFC);
  static const Color rampSecondary200 = Color(0xFFD0D9ED);
  static const Color rampSecondary300 = Color(0xFFB6C0D7);
  static const Color rampSecondary400 = Color(0xFF94A0B8);
  static const Color rampSecondary500 = Color(0xFF77829B);
  static const Color rampSecondary600 = Color(0xFF626C83);
  static const Color rampSecondary700 = Color(0xFF4D576B);
  static const Color rampSecondary800 = Color(0xFF3E4758);
  static const Color rampSecondary900 = Color(0xFF323948);
  static const Color rampSecondary950 = Color(0xFF0F172A);
  static const Color rampAccent50 = Color(0xFFF0F6FE);
  static const Color rampAccent100 = Color(0xFFE4EBF3);
  static const Color rampAccent200 = Color(0xFFCBD5E1);
  static const Color rampAccent300 = Color(0xFFB9C1CB);
  static const Color rampAccent400 = Color(0xFF98A1AC);
  static const Color rampAccent500 = Color(0xFF7A838E);
  static const Color rampAccent600 = Color(0xFF656D77);
  static const Color rampAccent700 = Color(0xFF505760);
  static const Color rampAccent800 = Color(0xFF41474F);
  static const Color rampAccent900 = Color(0xFF343940);
  static const Color rampAccent950 = Color(0xFF1B1F24);
  static const Color rampNeutral50 = Color(0xFFECF6FF);
  static const Color rampNeutral100 = Color(0xFFE0EBFB);
  static const Color rampNeutral200 = Color(0xFFCEDAEC);
  static const Color rampNeutral300 = Color(0xFFB4C1D5);
  static const Color rampNeutral400 = Color(0xFF92A1B6);
  static const Color rampNeutral500 = Color(0xFF748399);
  static const Color rampNeutral600 = Color(0xFF5F6D81);
  static const Color rampNeutral700 = Color(0xFF475569);
  static const Color rampNeutral800 = Color(0xFF3C4757);
  static const Color rampNeutral900 = Color(0xFF303947);
  static const Color rampNeutral950 = Color(0xFF191F28);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
