// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: http://127.0.0.1:63847/fixture.html
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x2563EB)
  static let actionSecondary = Color(hex: 0x0F172A)
  static let actionOnPrimary = Color(hex: 0xFFFFFF)
  static let actionOnSecondary = Color(hex: 0xFFFFFF)
  static let actionAccent = Color(hex: 0xCBD5E1)
  static let actionOnAccent = Color(hex: 0x000000)
  static let surfaceDefault = Color(hex: 0xF8FAFC)
  static let surfacePage = Color(hex: 0xF8FAFC)
  static let surfaceOnPage = Color(hex: 0x000000)
  static let surfaceRaised = Color(hex: 0xFFFFFF)
  static let surfaceOnRaised = Color(hex: 0x000000)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 8
  static let spacingS1: CGFloat = 80

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 8
  static let radiusR1: CGFloat = 12
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x2563EB)
  static let brandSecondary = Color(hex: 0x0F172A)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0x475569)
  static let neutralN400 = Color(hex: 0x94A3B8)
  static let backgroundBg0 = Color(hex: 0xF8FAFC)
  static let backgroundBg1 = Color(hex: 0xFFFFFF)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x0F172A)
  static let textText2 = Color(hex: 0x2563EB)
  static let textText3 = Color(hex: 0x475569)
  static let textText4 = Color(hex: 0xFFFFFF)
  static let textText5 = Color(hex: 0xCBD5E1)
  static let rampPrimary50 = Color(hex: 0xC7F5FF)
  static let rampPrimary100 = Color(hex: 0xB7E9FF)
  static let rampPrimary200 = Color(hex: 0xA0D7FF)
  static let rampPrimary300 = Color(hex: 0x80BCFF)
  static let rampPrimary400 = Color(hex: 0x5798FF)
  static let rampPrimary500 = Color(hex: 0x3777FF)
  static let rampPrimary600 = Color(hex: 0x2563EB)
  static let rampPrimary700 = Color(hex: 0x164ABE)
  static let rampPrimary800 = Color(hex: 0x0C3BA1)
  static let rampPrimary900 = Color(hex: 0x052D87)
  static let rampPrimary950 = Color(hex: 0x001654)
  static let rampSecondary50 = Color(hex: 0xEEF6FF)
  static let rampSecondary100 = Color(hex: 0xE1EAFC)
  static let rampSecondary200 = Color(hex: 0xD0D9ED)
  static let rampSecondary300 = Color(hex: 0xB6C0D7)
  static let rampSecondary400 = Color(hex: 0x94A0B8)
  static let rampSecondary500 = Color(hex: 0x77829B)
  static let rampSecondary600 = Color(hex: 0x626C83)
  static let rampSecondary700 = Color(hex: 0x4D576B)
  static let rampSecondary800 = Color(hex: 0x3E4758)
  static let rampSecondary900 = Color(hex: 0x323948)
  static let rampSecondary950 = Color(hex: 0x0F172A)
  static let rampAccent50 = Color(hex: 0xF0F6FE)
  static let rampAccent100 = Color(hex: 0xE4EBF3)
  static let rampAccent200 = Color(hex: 0xCBD5E1)
  static let rampAccent300 = Color(hex: 0xB9C1CB)
  static let rampAccent400 = Color(hex: 0x98A1AC)
  static let rampAccent500 = Color(hex: 0x7A838E)
  static let rampAccent600 = Color(hex: 0x656D77)
  static let rampAccent700 = Color(hex: 0x505760)
  static let rampAccent800 = Color(hex: 0x41474F)
  static let rampAccent900 = Color(hex: 0x343940)
  static let rampAccent950 = Color(hex: 0x1B1F24)
  static let rampNeutral50 = Color(hex: 0xECF6FF)
  static let rampNeutral100 = Color(hex: 0xE0EBFB)
  static let rampNeutral200 = Color(hex: 0xCEDAEC)
  static let rampNeutral300 = Color(hex: 0xB4C1D5)
  static let rampNeutral400 = Color(hex: 0x92A1B6)
  static let rampNeutral500 = Color(hex: 0x748399)
  static let rampNeutral600 = Color(hex: 0x5F6D81)
  static let rampNeutral700 = Color(hex: 0x475569)
  static let rampNeutral800 = Color(hex: 0x3C4757)
  static let rampNeutral900 = Color(hex: 0x303947)
  static let rampNeutral950 = Color(hex: 0x191F28)
}

// typography.body: family=Arial size=16px weight=400 lineHeight=normal
// typography.heading: family=Arial size=48px weight=700 lineHeight=52.8px
