'use strict';
const $=(s)=>document.querySelector(s);
const esc=(v)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
let category='全部',query='',current=SCENARIOS[0],activeFile='SKILL.md',apiMode='mcp';
const states={};
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function initialState(s){return {step:0,variant:0,format:'md',accepted:false,values:Object.fromEntries(s.fields.map(f=>[f[0],f[2]]))}}
function state(s=current){if(!states[s.id]){states[s.id]=initialState(s);try{const x=JSON.parse(localStorage.getItem('prompts-research-'+s.id));if(x&&x.values&&typeof x.values==='object'){s.fields.forEach(([key])=>{if(typeof x.values[key]==='string')states[s.id].values[key]=x.values[key].slice(0,12000)});states[s.id].variant=x.variant===1?1:0;states[s.id].accepted=x.accepted===true}}catch{}}return states[s.id]}
function fill(template,values){return template.replace(/\$\{([^}:]+)(?::([^}]*))?\}/g,(_,key,fallback)=>values[key]?.trim()||fallback||`[待填写：${key}]`)}
function template(s=current){let text=s.template;if(state(s).variant===1){const additions={research:'\n特别检查：依赖、环境变量、存储、模型接入和维护成本。',team:'\n输出升级条件、转交材料和待确认政策。',campaign:'\n侧重短视频：按开场、演示、收尾组织分镜。',agent:'\n侧重测试设计：列出正常、边界、失败与重试场景。',cleanup:'\n按讨论主题整理决策、行动项与待确认责任人。',private:'\n可选启用语义搜索与 AI 辅助改写；先明确外部服务的数据范围。'};text+=additions[s.id]}return text}
function prompt(s=current,enhanced=true){return fill(template(s),state(s).values)+(enhanced?'\n\n质量要求：\n'+s.extra:'')}
function skillFiles(){const v=state().values;return {'SKILL.md':`---\nname: review-workflow-demo\ndescription: 教学示例：按证据审查代码变更\n---\n\n# ${v.topic}审查方法\n\n${prompt()}\n\n## 步骤\n1. 阅读变更和接口约定。\n2. 根据 checklist.md 逐项检查。\n3. 给出问题证据与验证方法。\n4. 无法验证的部分明确标注。\n\n示例未安装、未执行。`, 'checklist.md':`# 审查清单\n\n技术环境：${v.audience}\n重点：${v.focus}\n\n- 输入边界与类型验证\n- 数据一致性与重复请求\n- 错误恢复和可观察性\n- 测试覆盖及失败证据\n\n本清单为教学示例，应结合代码调整。`, 'report-template.md':'# 审查报告结构\n\n## 结论\n## 已确认问题\n- 严重性\n- 文件与位置\n- 触发条件\n- 影响\n- 验证方法\n\n## 未验证项\n## 已运行检查与结果\n\n没有执行的检查不得写成已通过。'}}
function artifact(s=current){const st=state(s),v=st.values;let body=prompt(s);
 if(s.id==='campaign')body=`# ${v.topic} · 内容策划输入包\n\n## 统一简报\n${body}\n\n## 任务 1：文案\n为${v.audience}写一份围绕「${v.focus}」的发布文案；仅使用已知事实。\n\n## 任务 2：图像提示词\n主体：${v.topic}；风格和限制：${v.material}。构图需为主标题留白，输出前核对文字。\n\n## 任务 3：视频提示词\n围绕${v.focus}组织开场、功能演示和结尾；保持同一产品与视觉风格。\n\n交付检查：三个任务共用事实和品牌简报，媒体需在外部服务生成与验收。`;
 if(s.id==='agent')body=Object.entries(skillFiles()).map(([name,value])=>`===== ${name} =====\n${value}`).join('\n\n');
 if(s.id==='private')body=`# ${v.topic} · 部署需求清单\n\n${body}\n\n## 服务组成\n- Node.js 24.x 应用服务\n- PostgreSQL 数据库\n- 登录提供商与凭据\n- 备份、恢复与访问验证\n${st.variant===1?'- 外部模型服务配置与数据范围确认':'- 基础内容管理；AI 功能按需开启'}\n\n## 验收步骤\n1. 检查未登录访问。\n2. 用不同测试账号验证私有内容。\n3. 验证保存、版本记录和恢复。\n4. 如开启 MCP，验证只读查询与认证写入。\n5. 演练数据库备份恢复。\n\n这是一份部署规划，尚未执行安装。`;
 return {title:s.title,kind:'原创教学示例',scenario:s.id,template:template(s),variables:{...v},content:body,verification:'未调用上游服务或模型',...(s.id==='agent'?{files:skillFiles()}:{}),...(s.id==='team'?{review:st.accepted?'教学模拟：接受修改':'教学模拟：待审核'}:{})}}
function outputText(s=current){const a=artifact(s);return state(s).format==='json'?JSON.stringify(a,null,2):a.content}
function missing(){return current.fields.some(([key])=>!state().values[key]?.trim())}
function capLinks(ids){return ids.map(id=>{const c=CAPABILITIES.find(x=>x.id===id);return `<a href="#capabilities/${c.id}">${esc(c.title)} ↗</a>`}).join('')}
function renderCapabilities(focus){const items=CAPABILITIES.filter(c=>(category==='全部'||category===c.group)&&(!query||[c.title,c.desc,c.input,c.output,c.limit].join(' ').toLowerCase().includes(query.toLowerCase())));$('#cap-count').textContent=`显示 ${items.length} / ${CAPABILITIES.length} 项能力 · 点击条目展开`;
 $('#category-filters').innerHTML=['全部',...GROUPS].map(g=>`<button type="button" data-category="${esc(g)}" class="${category===g?'active':''}" aria-pressed="${category===g}">${esc(g)}</button>`).join('');
 $('#cap-list').innerHTML=items.length?GROUPS.map(g=>{const list=items.filter(c=>c.group===g);if(!list.length)return '';return `<div class="cap-group"><h2>${g}<small>${list.length} 项</small></h2><div class="cap-grid">${list.map(c=>`<details class="cap" id="cap-${c.id}" ${focus===c.id?'open':''}><summary><div><h3>${c.title}</h3><b aria-hidden="true">＋</b></div><p>${esc(c.desc)}</p></summary><div class="cap-detail"><dl><dt>输入</dt><dd>${esc(c.input)}</dd><dt>输出</dt><dd>${esc(c.output)}</dd><dt>边界</dt><dd>${esc(c.limit)}</dd></dl><span class="tag">${c.evidence}</span>${external(SOURCES[c.source][1],'查看证据')}<div class="cap-links">${SCENARIOS.filter(s=>s.caps.includes(c.id)).map(s=>`<a href="#scenarios/${s.id}">演练：${s.short} →</a>`).join('')}</div></div></details>`).join('')}</div></div>`}).join(''):'<div class="empty"><h3>没有找到匹配的能力</h3><p>试试“变量”“翻译”或切换到全部分类。</p><button class="action" data-clear-search>清除筛选</button></div>';
 if(focus)requestAnimationFrame(()=>document.getElementById('cap-'+focus)?.scrollIntoView({block:'center',behavior:'auto'}));}
function stageIntro(index){const s=current;const texts=[`本地候选用于说明「发现与选择」：${s.goal}`,`调整下列内容，生成的任务说明会使用这些参数。参数只在当前页面处理。`,`把模糊要求变成可核验的标准。下方建议为预先编写的教学内容。`,s.handoff,s.next];return texts[index]}
function formHTML(){return `<div class="stage-fields">${current.fields.map(([key,label])=>`<label class="field ${key==='material'?'full':''}">${esc(label)}${key==='material'?`<textarea rows="3" maxlength="12000" data-field="${key}">${esc(state().values[key])}</textarea>`:`<input maxlength="12000" data-field="${key}" value="${esc(state().values[key])}">`}</label>`).join('')}</div><div class="output-caption">填参后的任务说明 <span>实时预览</span></div><pre id="live-prompt" class="output">${esc(prompt(current,false))}</pre><p class="micro" id="missing-hint">${missing()?'请补齐所有字段后再导出。':'可以修改字段，观察同一个模板如何被复用。'}</p>`}
function choiceHTML(){return `<label class="field">在本地教学候选中查找<input id="candidate-search" type="search" placeholder="输入候选名称" autocomplete="off"></label><div class="choice-list" id="candidate-list">${current.choices.map((name,i)=>`<label class="choice" data-choice-label="${esc(name)}"><input type="radio" name="variant" value="${i}" ${state().variant===i?'checked':''}><span><strong>${esc(name)}</strong><small>原创示例 · ${i===0?'通用结构':'专项侧重'} · 可继续填写变量</small></span></label>`).join('')}</div><p class="micro" id="candidate-empty" hidden>没有匹配候选，试试清空搜索词。</p><p class="micro">这里只搜索上面的两个教学候选；真实社区检索请使用上游网站。</p><pre class="output" id="selected-template">${esc(template())}</pre>`}
function refineHTML(){if(current.id==='agent'){const files=skillFiles();if(!files[activeFile])activeFile='SKILL.md';return `<div class="code-tabs" aria-label="技能文件">${Object.keys(files).map(name=>`<button class="${name===activeFile?'active':''}" data-file="${name}" aria-pressed="${name===activeFile}">${name}</button>`).join('')}</div><pre class="output dark">${esc(files[activeFile])}</pre><p class="micro">三份原创文件组成教学技能。没有自动安装，也没有运行任何脚本。</p>`}
 if(current.id==='private')return `<div class="integration-flow"><article><h3>内容管理</h3><p>私有提示词、分类、标签与版本。</p></article><article><h3>登录方式</h3><p>按组织选择已有身份提供商，配置凭据。</p></article><article><h3>${state().variant===1?'AI 辅助':'基础模式'}</h3><p>${state().variant===1?'语义搜索与改写需要模型配置。':'先管理内容，AI 功能按需开启。'}</p></article><article><h3>工具访问</h3><p>MCP 与 API Key 按需求配置。</p></article></div><div class="review-note">${esc(current.extra)}</div>`;
 if(current.id==='cleanup')return `<div class="editor-grid"><div><div class="output-caption">不同来源的变量形式</div><pre class="output">请为 {{topic}} 整理进展，面向 [AUDIENCE]。</pre></div><div><div class="output-caption">统一后的教学示例</div><pre class="output">请为 &#36;{topic} 整理进展，面向 &#36;{audience}。</pre></div></div><h3>批量整理时需要检查</h3><ul><li>变量是否都能被填入？</li><li>任务、材料、输出和限制是否齐全？</li><li>相近文本是否只是写法不同，是否仍需保留？</li></ul><p class="micro">这是结构说明，未调用上游 SDK 评分或相似度算法。</p><div class="review-note">${esc(current.extra)}</div>`;
 return `<div class="editor-grid"><div><div class="output-caption">原始任务说明</div><pre class="output minus">${esc(prompt(current,false))}</pre></div><div><div class="output-caption">建议新增的要求</div><pre class="output plus">${esc(current.extra)}</pre></div></div><p class="micro">此处展示人工预设的前后对比，未调用 improve_prompt。</p>`}
function executionHTML(){if(current.id==='agent'){const packets=[{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'search_skills',arguments:{query:state().values.focus}}},{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'get_skill',arguments:{id:'DEMO_SKILL_ID'}}}];return `<div class="output-caption">请求结构示例 · 未发送</div><pre class="output dark">${esc(JSON.stringify(packets,null,2))}</pre><div class="review-note">取回文件 → 检查内容与依赖 → 安装到相应客户端 → 提供代码和材料 → 执行审查与验证。实际命令取决于客户端。</div>`}
 if(current.id==='team')return `<div class="editor-grid"><article class="panel"><span class="tag">教学 v1</span><h3>只有答复要求</h3><p>缺少订单信息时，容易直接输出听起来完整的回复。</p></article><article class="panel"><span class="tag">教学 v2 提案</span><h3>增加核实与升级规则</h3><p>${esc(current.extra)}</p></article></div><div class="action-row"><button class="action primary" data-review ${state().accepted?'disabled':''}>${state().accepted?'已在本演练中接受':'模拟接受修改'}</button></div><p class="review-note" id="review-status">${state().accepted?'教学状态：v2 已接受。仅影响本页，未创建上游版本。':'教学状态：等待审核。真实协作应检查修改理由和业务政策。'}</p>`;
 if(current.id==='private')return `<div class="integration-flow"><article><h3>01 使用者</h3><p>浏览器或 MCP 客户端</p></article><article><h3>02 自有应用</h3><p>登录、鉴权、检索与接口</p></article><article><h3>03 存储</h3><p>PostgreSQL 与备份</p></article><article><h3>04 可选服务</h3><p>${state().variant===1?'外部模型或媒体服务':'暂不启用 AI 功能'}</p></article></div><div class="review-note">${esc(current.extra)}</div>`;
 if(current.id==='campaign')return `<div class="integration-flow"><article><h3>共享简报</h3><p>${esc(state().values.topic)}</p></article><article><h3>文案任务</h3><p>信息组织与事实核验</p></article><article><h3>图像任务</h3><p>画面、风格与文字核验</p></article><article><h3>视频任务</h3><p>分镜、节奏与一致性</p></article></div><pre class="output">${esc(artifact().content)}</pre>`;
 if(current.id==='cleanup')return `<div class="output-caption">整理后的资源结构 · 本页实际生成</div><pre class="output dark">${esc(JSON.stringify(artifact(),null,2))}</pre>`;
 return `<div class="output-caption">准备交给模型的任务书</div><pre class="output">${esc(prompt())}</pre><div class="review-note">验收顺序：查看来源 → 对照事实 → 标注未验证项 → 决定是否值得进一步实测。</div>`}
function exportHTML(){return `<div class="output-caption"><span>${current.id==='agent'?'技能文件汇总（非安装包）':'可带走的示例成果'}</span><label>格式 <select id="export-format"><option value="md" ${state().format==='md'?'selected':''}>文本 / Markdown</option><option value="json" ${state().format==='json'?'selected':''}>JSON</option></select></label></div><pre class="output" id="final-output">${esc(outputText())}</pre><div class="action-row"><button class="action primary" data-copy ${missing()?'disabled':''}>复制内容</button><button class="action" data-download ${missing()?'disabled':''}>下载示例</button><button class="action" data-save ${missing()?'disabled':''}>保存本机草稿</button></div><p class="micro">${missing()?'请返回“填写”步骤补齐内容。':'保存只写入当前浏览器，不上传至 prompts.chat。下载为原创示例文本，未包含模型生成成果。'} ${current.id==='team'&&!state().accepted?'当前修改仍是待审核提案。':''}</p>`}
function renderScenario(){const s=current,st=state();$('#scenario-tabs').innerHTML=SCENARIOS.map(x=>`<a href="#scenarios/${x.id}" class="${s.id===x.id?'active':''}" ${s.id===x.id?'aria-current="page"':''}>${x.short}<span aria-hidden="true"> · </span>${x.title.split(' → ')[1]}</a>`).join('');
 $('#scenario-workspace').innerHTML=`<div class="workspace"><div class="workspace-header"><div><h2>${s.title}</h2><p>${s.goal}</p></div><span class="tag">${st.step+1} / ${s.steps.length}</span></div><div class="workspace-body"><nav class="stepper" aria-label="演练步骤">${s.steps.map((x,i)=>`<button data-step="${i}" class="${st.step===i?'active':''}" ${st.step===i?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${x}</button>`).join('')}</nav><div class="stage"><div class="stage-top"><h3>${s.steps[st.step]}</h3><span class="tag">STEP ${st.step+1}</span></div><p class="hint">${stageIntro(st.step)}</p>${[choiceHTML,formHTML,refineHTML,executionHTML,exportHTML][st.step]()}<div class="cap-links">${capLinks(s.caps)}</div><div class="step-footer"><button class="action" data-prev ${st.step===0?'disabled':''}>← 上一步</button>${st.step<4?'<button class="action primary" data-next>下一步 →</button>':'<button class="action" data-restart>从头演练</button>'}</div></div></div></div><div class="action-row"><button class="action" data-reset>重置此场景</button><span class="micro">会清除该场景在本浏览器保存的示例草稿。</span></div>`;}
function integrationCode(mode){const code={mcp:'{\n  "mcpServers": {\n    "prompts.chat": {\n      "url": "https://prompts.chat/api/mcp"\n    }\n  }\n}',cli:'npx prompts.chat\n\n# 本地 MCP 入口（仍可能访问远程数据）\nnpx prompts.chat mcp',plugin:'/plugin marketplace add f/prompts.chat\n/plugin install prompts.chat@prompts.chat\n\n/prompts.chat:prompts code review\n/prompts.chat:skills testing',sdk:"import { builder, variables, quality } from 'prompts.chat';\n\nconst prompt = builder()\n  .role('项目研究员')\n  .task('整理项目能力和验证边界')\n  .constraints(['附上来源', '不编造运行结果'])\n  .build();\n\n// 本地文字规则检查，不等于模型效果评测\nconst result = quality.check('请根据提供的资料整理能力表。');",http:'GET https://prompts.chat/api/prompts?q=code+review&perPage=10\nGET https://prompts.chat/api/prompts/{id}\n\nPOST https://prompts.chat/api/mcp\n# 写入和私有访问需要在客户端安全配置认证'};return code[mode]}
function renderIntegration(){const routes=[['网站','浏览、收藏、维护模板','个人快速开始','账号按操作需要登录'],['MCP','助手查询、读取、保存资源','在已有 Agent 中复用','客户端支持 + 按需认证'],['CLI / 插件','终端查找、复制、打开平台','开发过程少切换窗口','运行环境与远程服务'],['开发工具包','在程序里构建、处理模板','批量整理与开发集成','Node.js 项目依赖'],['自行托管','管理自有内容和访问入口','内部资源库与品牌定制','应用 + 数据库 + 登录配置']];const tools=[['search_prompts / get_prompt','查找与读取提示词','公开内容通常无需认证；私有内容需认证'],['save_prompt / improve_prompt','保存与 AI 改写','需要认证；改写还需模型配置'],['search_skills / get_skill','查找与读取多文件技能','私有资源需认证'],['save_skill','创建含 SKILL.md 的技能','需要认证'],['add_file_to_skill / update_skill_file / remove_file_from_skill','增删改技能文件','需要认证及资源权限']];
 $('#integration-content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>入口</th><th>主要用途</th><th>适合场景</th><th>前提</th></tr></thead><tbody>${routes.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')}</tbody></table></div><div class="section-heading"><div><div class="eyebrow">接入参考</div><h2>配置和命令，放在需要的时候看</h2></div></div><p class="micro">下面是文档中的接入方式示意，不会自动执行。MCP 配置格式因客户端不同而异；不在网页填写 API Key。</p><div class="code-tabs" aria-label="接入类型">${[['mcp','MCP'],['cli','CLI'],['plugin','Claude Code 插件'],['sdk','开发工具包'],['http','HTTP']].map(([id,t])=>`<button data-api="${id}" class="${apiMode===id?'active':''}" aria-pressed="${apiMode===id}">${t}</button>`).join('')}</div><pre class="output dark" id="integration-code">${esc(integrationCode(apiMode))}</pre><button class="action" data-copy-api>复制当前示例</button><div class="section-heading"><h2>MCP：固定版本中的 10 个工具</h2></div><div class="table-wrap"><table><thead><tr><th>工具</th><th>作用</th><th>访问条件</th></tr></thead><tbody>${tools.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')}</tbody></table></div><p class="micro">工具注册已从固定版本源码核对，未进行在线调用。另有 prompts/list 和 prompts/get 协议能力；不计入上述 10 个工具。${external(SOURCES.mcp[1],'查看 MCP 源码')}</p><div class="section-heading"><h2>自行托管：四层需要一起考虑</h2></div><div class="integration-flow"><article><h3>应用服务</h3><p>Node.js 24.x；Next.js、React 与 Prisma 组成网站。</p></article><article><h3>持久数据</h3><p>PostgreSQL 存储用户、提示词、版本和关系。</p></article><article><h3>认证与配置</h3><p>配置登录提供商、品牌主题和功能开关。</p></article><article><h3>可选 AI 服务</h3><p>语义搜索、生成、翻译和媒体功能依赖提供商。</p></article></div><div class="action-row"><a class="button primary" href="#scenarios/private">演练私有库规划 →</a>${external(SOURCES.hosting[1],'官方部署文档')}</div><div class="boundary-strip"><strong>网页静态托管和上游完整部署，是两件事。</strong><p>本研究网页无需数据库；上游完整应用需要服务端、持久存储和认证。上游具备配置入口不等于已完成企业权限、安全或容量验证。</p></div>`;}
function route(){const parts=location.hash.slice(1).split('/');let view=parts[0]||'guide';if(!['guide','library','reference','playbook','catalog','recipes','overview','capabilities','scenarios','integration','evidence'].includes(view))view='guide';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('#nav a').forEach(el=>{const yes=el.hash==='#'+(view==='reference'?'guide':view);el.classList.toggle('active',yes);if(yes)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});if(view==='guide')renderGuide(parts[1]);if(view==='library')renderLibrary(parts.slice(1));if(view==='reference')renderReference(parts[1]);if(view==='playbook')renderPlaybook(parts[1]);if(view==='catalog')renderCatalog(parts[1]);if(view==='recipes')renderRecipes(parts[1]);if(view==='scenarios'){current=SCENARIOS.find(s=>s.id===parts[1])||SCENARIOS[0];renderScenario()}if(view==='capabilities'){if(parts[1]){category='全部';query='';$('#cap-search').value=''}renderCapabilities(parts[1])}if(view==='integration')renderIntegration();window.scrollTo({top:0,behavior:'instant'});document.title=`${({guide:'用途与价值地图',library:'完整公开索引',reference:'提示词阅读说明',playbook:'我们的复用路径',catalog:'Design 提示词专题',recipes:'真实条目组合使用',overview:'认识这个库',capabilities:'能力全景',scenarios:'场景演练',integration:'接入与部署',evidence:'边界与资料'})[view]} · prompts.chat 提示词目录`;}
async function copy(text){try{if(!navigator.clipboard?.writeText)throw Error('clipboard');await navigator.clipboard.writeText(text);toast('已复制到剪贴板')}catch{toast('当前浏览器无法复制，请选中内容手动复制或下载文件。')}}
function download(){if(missing()){toast('请先补齐所有字段');return}const text=outputText();const url=URL.createObjectURL(new Blob([text],{type:state().format==='json'?'application/json;charset=utf-8':'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`prompts-chat-${current.id}-demo.${state().format==='json'?'json':'md'}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已准备示例文件下载')}
function step(n){state().step=Math.max(0,Math.min(4,n));renderScenario()}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;
 if(t.dataset.category){category=t.dataset.category;renderCapabilities()}
 if(t.hasAttribute('data-clear-search')){category='全部';query='';$('#cap-search').value='';renderCapabilities()}
 if(t.dataset.step!==undefined)step(Number(t.dataset.step));
 if(t.hasAttribute('data-next')){if(state().step===1&&missing()){toast('请补齐所有字段后继续');return}step(state().step+1)}
 if(t.hasAttribute('data-prev'))step(state().step-1);
 if(t.hasAttribute('data-restart'))step(0);
 if(t.dataset.file){activeFile=t.dataset.file;renderScenario()}
 if(t.hasAttribute('data-review')){state().accepted=true;renderScenario();toast('已模拟接受修改；没有写入上游')}
 if(t.hasAttribute('data-copy'))copy(outputText());
 if(t.hasAttribute('data-download'))download();
 if(t.hasAttribute('data-save')){try{localStorage.setItem('prompts-research-'+current.id,JSON.stringify({values:state().values,variant:state().variant,accepted:state().accepted}));toast('已保存到本浏览器，下次打开会恢复填写内容')}catch{toast('浏览器存储不可用，请下载示例保留内容')}}
 if(t.hasAttribute('data-reset')){states[current.id]=initialState(current);try{localStorage.removeItem('prompts-research-'+current.id)}catch{}renderScenario();toast('已重置此场景')}
 if(t.dataset.api){apiMode=t.dataset.api;renderIntegration()}
 if(t.hasAttribute('data-copy-api'))copy(integrationCode(apiMode));
});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='cap-search'){query=t.value.trim();renderCapabilities()}if(t.dataset.field){state().values[t.dataset.field]=t.value;$('#live-prompt').textContent=prompt(current,false);$('#missing-hint').textContent=missing()?'请补齐所有字段后再导出。':'字段已更新，任务说明同步变化。'}if(t.id==='candidate-search'){let count=0;document.querySelectorAll('[data-choice-label]').forEach(el=>{el.hidden=!el.dataset.choiceLabel.includes(t.value.trim());if(!el.hidden)count++});$('#candidate-empty').hidden=count>0}});
document.addEventListener('change',e=>{const t=e.target;if(t.name==='variant'){state().variant=Number(t.value);$('#selected-template').textContent=template()}if(t.id==='export-format'){state().format=t.value;$('#final-output').textContent=outputText()}});
$('#nav-count').textContent=CAPABILITIES.length;
$('#scenario-shortcuts').innerHTML=SCENARIOS.map((s,i)=>`<a class="shortcut" href="#scenarios/${s.id}"><span class="num">SCENARIO ${String(i+1).padStart(2,'0')}</span><h3>${s.title}</h3><p>${s.desc}</p></a>`).join('');
$('#limits').innerHTML=LIMITS.map(([title,body])=>`<details class="disclosure"><summary>${title}</summary><p>${body}</p></details>`).join('');
$('#sources').innerHTML=Object.entries(SOURCES).map(([id,[title,url,desc]])=>`<article class="source" id="source-${id}"><strong>${external(url,title)}</strong><p>${desc}</p></article>`).join('');
$('#commit-link').href=BASE.replace('blob/','tree/').replace(/\/$/,'');
window.addEventListener('hashchange',route);route();
