'use strict';
const CATALOG_GROUPS=['全部','网站与 UI','规范与开发交接','检查与上线','品牌与海报','插画与图像','游戏与音视频','Skill 条目'];
const CATALOG_TYPES={TEXT:'文本提示词',IMAGE:'图像标签',SKILL:'Skill 标签'};
let catalogGroup='全部',catalogQuery='',catalogType='全部',catalogReadiness='全部';
const personalContexts={};
const RECIPES=[
 {id:'new-site',title:'从想法开始，做一个网站',example:'例子：给一个读书笔记工具做介绍网站。',brief:'你准备产品介绍、受众、参考网站和需要的页面。每一步把上一阶段确认的结果带到下一步。',steps:[
  ['cmmnb9dxg0001l8047jcrujr5','先确定方向','填品牌、受众、页面和参考风格。','得到设计概念、布局和配色方向；先确认，再往下走。'],
  ['cmmxtz3690005l704lv6dp3h5','把方向变成 UI 规则','带上已确认的概念、主要操作和页面清单。','得到字体、颜色、间距、组件和状态的统一规则。'],
  ['cmmxtsuq40001l704dlqlgxdr','交给开发者实现','带上页面方案和 UI 规则。','得到组件树、状态和实现说明；再让编码工具写代码。'],
  ['cmmoq1aqr000kle046h0960yk','对照方案检查网页','提供可运行网页与原设计，给具备浏览器能力的助手。','获得偏差和交互问题清单；修复后重新检查。'],
  ['cmmoq6w7o0004la042h9mga36','发布前逐项验收','带上关键功能、发布方式和已知问题。','得到上线清单；实际完成检查后再发布。']
 ]},
 {id:'existing-site',title:'接手旧网站，整理后再改造',example:'例子：后台页面的按钮、字体和间距各不相同。',brief:'先从已有代码和界面确认现状，再决定哪些规则要保留、哪些要统一。',steps:[
  ['cmmoikk3b000jkz04xgxb1t9s','提取现有设计规则','提供代码、框架、样式方案和组件目录。','得到现状报告，盘点颜色、字体、间距与组件。'],
  ['cmmxtuy2w0004l704mt7xxlr3','找出不一致的地方','把现状报告和代表页面交给助手。','得到问题清单、统一方向和修复优先级。'],
  ['cmobfhjz3000el1043ccbflbw','比较外观改造方向','提供现有功能清单与需要保留的操作。','得到几种视觉方案；选定后再进入实现。'],
  ['cmmopznp10009le041evkm0nx','写清实现细节','用已确认的设计、组件和状态填写长版交接模板。','得到细化的实施说明；先裁剪不适用的章节。'],
  ['cmmoq2i9d000sle049zrs991x','根据真实数据优化性能','提供新页面和实际性能检测报告。','得到图片、字体、脚本等方面的优化行动。']
 ]},
 {id:'brand',title:'为品牌准备 Logo 与活动海报',example:'例子：为社区读书会准备统一的标志和宣传图。',brief:'先形成品牌简报，再用参考图描述风格，最后交给能出图的工具制作。',steps:[
  ['cmrlz4j1p0001i20abdmz1zik','问清品牌想表达什么','填项目名称、受众与品牌色，回答澄清问题。','得到 Logo 的文字概念，供选择和进一步制作。'],
  ['cmn089nzq0004l104lmz1atha','提取参考图片的风格','提供有权使用的插画参考图。','得到颜色、线条、阴影和风格标签，供新画面复用。'],
  ['cmqqhqp87000el204uh69zoup','准备海报的生成要求','带上活动内容、参考图和确认的角色／人物。','得到海报需求，或由具备图像能力的工具实际出图。']
 ]}
];
function catalogMatches(){return PROMPT_CATALOG.prompts.filter(p=>(catalogGroup==='全部'||p.group===catalogGroup)&&(catalogType==='全部'||p.sourceType===catalogType)&&(catalogReadiness==='全部'||p.readiness===catalogReadiness)&&(!catalogQuery||[p.zhTitle,p.title,p.job,p.input,p.output,p.note,p.example].join(' ').toLowerCase().includes(catalogQuery.toLowerCase())))}
function catalogContext(p){if(!personalContexts[p.id])personalContexts[p.id]={task:p.example,materials:'',requirements:''};return personalContexts[p.id]}
function contextualPrompt(p){const c=catalogContext(p);return `${p.rawContent}\n\n---\n本次任务补充（请结合以上模板处理）：\n我的任务：${c.task.trim()||'【请补充任务】'}\n我提供的材料：${c.materials.trim()||'【请在使用前补充材料】'}\n我的具体要求：${c.requirements.trim()||'按模板组织结果，先指出还缺少哪些必要信息。'}\n\n请以中文回应。原模板中的示例、占位符或固定人物／品牌／日期，先与本次任务核对；有冲突时向我确认。没有提供或没有实际检查的信息，请明确说明，不要编造已完成的结果。`}
function rawDownload(p,adapted=false){const text=adapted?contextualPrompt(p):p.rawContent;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${p.id}-${adapted?'my-task':'original'}.txt`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已准备提示词文本下载')}
function catalogCard(p){return `<article class="prompt-card"><div class="prompt-card-meta"><span>${esc(p.group)}</span><span class="readiness ${p.readiness==='未完成骨架'?'incomplete':''}">${esc(p.readiness)}</span></div><h2><a href="#catalog/${p.id}">${esc(p.zhTitle)}</a></h2><p class="original-title">${esc(p.title)}</p><p class="prompt-job">${esc(p.job)}</p><dl><dt>你提供</dt><dd>${esc(p.input)}</dd><dt>希望得到</dt><dd>${esc(p.output)}</dd></dl><div class="prompt-card-bottom"><span class="micro">官网标记：${CATALOG_TYPES[p.sourceType]||esc(p.sourceType)}</span><a href="#catalog/${p.id}">原文与用法 →</a></div></article>`}
function renderCatalogList(){const result=catalogMatches();$('#prompt-groups').innerHTML=CATALOG_GROUPS.map(g=>`<button class="${catalogGroup===g?'active':''}" data-prompt-group="${esc(g)}" aria-pressed="${catalogGroup===g}">${esc(g)} <span>${g==='全部'?PROMPT_CATALOG.prompts.length:PROMPT_CATALOG.prompts.filter(p=>p.group===g).length}</span></button>`).join('');$('#prompt-count').textContent=`当前显示 ${result.length} / 30 条 · 按任务理解程度整理，未做效果排名`;
 $('#prompt-cards').innerHTML=result.length?result.map(catalogCard).join(''):'<div class="empty"><h2>没有匹配的提示词</h2><p>试试“网站”“字体”“海报”，或清除筛选。</p><button class="action" data-reset-catalog>清除筛选</button></div>';
}
function renderPromptDetail(id){const p=PROMPT_CATALOG.prompts.find(x=>x.id===id);if(!p)return false;const c=catalogContext(p);const recipeLinks=RECIPES.filter(r=>r.steps.some(s=>s[0]===p.id));
 $('#prompt-detail').innerHTML=`<a class="backlink" href="#catalog">← 返回 30 条提示词</a><div class="prompt-detail-heading"><div><div class="eyebrow">${esc(p.group)} / 真实条目</div><h1>${esc(p.zhTitle)}</h1><p class="detail-original-title">官网原标题：${esc(p.title)}</p></div><span class="readiness ${p.readiness==='未完成骨架'?'incomplete':''}">${esc(p.readiness)}</span></div><p class="lead">${esc(p.job)}</p><div class="detail-columns"><div><div class="task-summary"><div><span>你需要准备</span><p>${esc(p.input)}</p></div><div><span>它希望 AI 输出</span><p>${esc(p.output)}</p></div></div><div class="concrete-example"><span class="eyebrow">放到具体工作里</span><p>${esc(p.example)}</p></div><div class="prompt-note"><strong>读过原文后，需要注意</strong><p>${esc(p.note)}</p></div></div><aside class="source-aside"><h2>这是一条任务说明</h2><ol><li>阅读并调整内容</li><li>补充你的材料</li><li>交给具备相应能力的 AI</li><li>检查得到的结果</li></ol><p>${p.sourceType==='SKILL'?'这条虽然标为 Skill，但步骤尚未写完。应先完善内容。':'通常复制给 AI 即可，不需要安装。'}</p><div class="source-links">${external(p.sourceUrl,'去官网看这条')}<span>官网类型：${CATALOG_TYPES[p.sourceType]}</span><span>采集：${PROMPT_CATALOG.meta.capturedAt}</span></div></aside></div>
 <section class="raw-section"><div class="section-heading"><div><div class="eyebrow">保留原文，不改写成另一条</div><h2>实际收录的提示词</h2></div><span class="micro">${p.rawContent.length.toLocaleString()} 字符 · 原文语言保留</span></div><details class="raw-prompt"><summary>展开完整原文</summary><pre class="output raw-content">${esc(p.rawContent)}</pre></details><div class="action-row"><button class="action" data-copy-original="${p.id}">复制原始提示词</button><button class="action" data-download-original="${p.id}">下载原文</button></div></section>
 <section class="use-real-prompt"><div class="section-heading"><div><div class="eyebrow">试着用在自己的事情上</div><h2>在原文后补上你的任务</h2></div></div><p class="hint">这里保留整条原文，附加你的背景和材料说明。只整理输入，不调用模型；必要时仍需修改原文中的固定要求。</p><div class="stage-fields"><label class="field full">我现在想做什么<textarea rows="2" maxlength="12000" data-context-id="${p.id}" data-context-key="task">${esc(c.task)}</textarea></label><label class="field full">我能提供什么材料<textarea rows="2" maxlength="12000" data-context-id="${p.id}" data-context-key="materials" placeholder="${esc(p.input)}">${esc(c.materials)}</textarea></label><label class="field full">有什么特别要求<textarea rows="2" maxlength="12000" data-context-id="${p.id}" data-context-key="requirements" placeholder="例如：先提问再开始；只分析指定页面；输出中文清单。">${esc(c.requirements)}</textarea></label></div><details class="raw-prompt"><summary>预览准备交给 AI 的完整内容</summary><pre id="contextual-output" class="output raw-content">${esc(contextualPrompt(p))}</pre></details><div class="action-row"><button class="action primary" data-copy-context="${p.id}">复制原文＋我的任务</button><button class="action" data-download-context="${p.id}">下载待使用文本</button></div><p class="micro">未填写的材料会保留“请补充”标记。实际图片、代码和检测报告还需在你使用的 AI 工具里提供。当前填写内容只留在页面内存。</p></section>
 ${recipeLinks.length?`<div class="section-heading"><h2>这条可以与哪些提示词配合？</h2></div><div class="recipe-links">${recipeLinks.map(r=>`<a class="button" href="#recipes/${r.id}">${esc(r.title)} →</a>`).join('')}</div>`:''}<p class="micro source-footnote">中文标题、用途、准备材料及提醒为本研究整理；完整原文来自官网公开接口，适用上游 CC0 内容许可。收录不代表效果已验证。</p>`;return true;
}
function renderCatalog(id){const detail=id&&renderPromptDetail(id);$('#catalog-list').hidden=!!detail;$('#prompt-detail').hidden=!detail;if(!detail)renderCatalogList();}
function renderRecipes(id='new-site'){const recipe=RECIPES.find(r=>r.id===id)||RECIPES[0];$('#real-recipe-tabs').innerHTML=RECIPES.map(r=>`<a href="#recipes/${r.id}" class="${r.id===recipe.id?'active':''}" ${r.id===recipe.id?'aria-current="page"':''}>${esc(r.title)}</a>`).join('');$('#real-recipe-content').innerHTML=`<div class="recipe-intro"><h2>${recipe.title}</h2><p class="recipe-example">${recipe.example}</p><p>${recipe.brief}</p></div><div class="real-recipe-steps">${recipe.steps.map(([id,title,input,output],i)=>{const p=PROMPT_CATALOG.prompts.find(x=>x.id===id);return `<article class="real-step"><div class="real-step-number">${String(i+1).padStart(2,'0')}</div><div><span class="eyebrow">${i===0?'从你的需求开始':'带上上一阶段的结果'}</span><h2>${title}</h2><a class="recipe-prompt-title" href="#catalog/${id}">${esc(p.zhTitle)} ↗</a><p class="original-title">${esc(p.title)}</p><dl><dt>交给 AI</dt><dd>${esc(input)}</dd><dt>得到后</dt><dd>${esc(output)}</dd></dl><a class="button" href="#catalog/${id}">打开这条原文，填我的任务 →</a></div></article>`}).join('')}</div><div class="boundary-strip"><strong>这是我们用真实条目整理的使用顺序。</strong><p>不是官网提供的一键工作流，也不是已运行的生成案例。你需要确认上一阶段的结果，再将它交给下一条提示词；编码、看图、浏览器检查或出图，需要对应工具能力。</p></div>`;}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.promptGroup){catalogGroup=t.dataset.promptGroup;renderCatalogList()}if(t.hasAttribute('data-reset-catalog')){catalogGroup='全部';catalogQuery='';catalogType='全部';catalogReadiness='全部';$('#prompt-search').value='';$('#prompt-type').value='全部';$('#prompt-readiness').value='全部';renderCatalogList()}
 for(const [key,fn] of [['copyOriginal',p=>copy(p.rawContent)],['downloadOriginal',p=>rawDownload(p)],['copyContext',p=>copy(contextualPrompt(p))],['downloadContext',p=>rawDownload(p,true)]]){if(t.dataset[key]){const p=PROMPT_CATALOG.prompts.find(x=>x.id===t.dataset[key]);if(p)fn(p)}}
});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='prompt-search'){catalogQuery=t.value.trim();renderCatalogList()}if(t.dataset.contextId&&t.dataset.contextKey){const p=PROMPT_CATALOG.prompts.find(x=>x.id===t.dataset.contextId);if(!p)return;catalogContext(p)[t.dataset.contextKey]=t.value;$('#contextual-output').textContent=contextualPrompt(p)}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='prompt-type'){catalogType=t.value;renderCatalogList()}if(t.id==='prompt-readiness'){catalogReadiness=t.value;renderCatalogList()}});
